# Generated by Django 4.2.9 on 2025-01-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='name',
            new_name='business_name',
        ),
    ]
