# Generated by Django 4.2.16 on 2025-01-02 13:12

import backend.enums
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBatch',
            fields=[
                ('orderBatch_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('initiated_at', models.IntegerField(default=1735823579)),
                ('created_at', models.IntegerField(default=1735823579)),
                ('order_type', models.CharField(choices=[('PROVISIONING', 'Provisioning'), ('SALE', 'Sale'), ('BACKORDER', 'Backorder'), ('RETURN', 'Return'), ('EXCHANGE', 'Exchange'), ('TRIAL', 'Trial'), ('GIFT', 'Gift'), ('PROMOTIONAL', 'Promotional'), ('STOCK_ADJUSTMENT', 'Stock Adjustment'), ('INTERNAL_TRANSFER', 'Internal Transfer'), ('PURCHASE_ORDER', 'Purchase Order'), ('STOCK_DAMAGE', 'Stock Damage'), ('STOCK_RETURN', 'Stock Return')], max_length=20)),
                ('total_order_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dispatch_type', models.CharField(choices=[('STORE', 'Store'), ('SHIPPING', 'Shipping')], max_length=20)),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('POS', 'POS'), ('UPI', 'UPI'), ('CHECK', 'Check'), ('COMPANY_CREDIT', 'Company Credit')], max_length=20)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Pending'), ('REFUNDED', 'Refunded'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=20)),
                ('payment_id', models.UUIDField(default='a2d5a8d6-bccf-5b26-b0e9-4b5ab8cf38f1')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orderBatch_id', models.UUIDField(db_index=True)),
                ('org_id', models.UUIDField(db_index=True)),
                ('order_status', models.CharField(choices=[('PROVISIONING', 'Provisioning'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default=backend.enums.OrderStatus['PROVISIONING'], max_length=20)),
                ('productBatch_id', models.UUIDField()),
                ('order_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_type', models.CharField(choices=[('KG', 'Kilogram'), ('METER', 'Meter'), ('LITRE', 'Litre'), ('PACK', 'Pack'), ('PIECE', 'Piece')], max_length=20)),
                ('planned_delivery', models.DateField()),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
    ]
