# Generated by Django 4.2.9 on 2025-01-21 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_svs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbatch',
            name='created_at',
            field=models.IntegerField(default=1737478230),
        ),
        migrations.AlterField(
            model_name='orderbatch',
            name='updated_at',
            field=models.IntegerField(default=1737478230),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='actual_delivery',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 21, 16, 50, 30, 401780, tzinfo=datetime.timezone.utc)),
        ),
    ]
