# Generated by Django 4.2.16 on 2025-01-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_svs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbatch',
            name='created_at',
            field=models.IntegerField(default=1735832082),
        ),
        migrations.AlterField(
            model_name='orderbatch',
            name='initiated_at',
            field=models.IntegerField(default=1735832082),
        ),
        migrations.AlterField(
            model_name='orderbatch',
            name='order_type',
            field=models.CharField(choices=[('PROVISIONING', 'Provisioning'), ('SALE', 'Sale'), ('BACKORDER', 'Backorder'), ('RETURN', 'Return'), ('EXCHANGE', 'Exchange'), ('TRIAL', 'Trial'), ('GIFT', 'Gift'), ('PROMOTIONAL', 'Promotional'), ('STOCK_ADJUSTMENT', 'Stock Adjustment'), ('INTERNAL_TRANSFER', 'Internal Transfer'), ('PURCHASE_ORDER', 'Purchase Order'), ('STOCK_DAMAGE', 'Stock Damage'), ('STOCK_RETURN', 'Stock Return'), ('STOCK_ENTRY', 'Stock Entry')], max_length=20),
        ),
    ]
