# Generated by Django 4.2.16 on 2025-01-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_svs', '0002_alter_orderbatch_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbatch',
            name='created_at',
            field=models.IntegerField(default=1735832331),
        ),
        migrations.AlterField(
            model_name='orderbatch',
            name='initiated_at',
            field=models.IntegerField(default=1735832331),
        ),
    ]
