# Generated by Django 4.2.16 on 2025-01-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_svs', '0003_alter_orderbatch_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbatch',
            name='initiated_at',
        ),
        migrations.AddField(
            model_name='orderbatch',
            name='updated_at',
            field=models.IntegerField(default=1735833253),
        ),
        migrations.AlterField(
            model_name='orderbatch',
            name='created_at',
            field=models.IntegerField(default=1735833253),
        ),
    ]
