# Generated by Django 4.2.16 on 2025-01-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_svs', '0004_remove_orderbatch_initiated_at_orderbatch_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbatch',
            name='created_at',
            field=models.IntegerField(default=1735839673),
        ),
        migrations.AlterField(
            model_name='orderbatch',
            name='updated_at',
            field=models.IntegerField(default=1735839673),
        ),
    ]
