# Generated by Django 4.2.16 on 2025-01-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_svs', '0007_alter_orderbatch_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbatch',
            name='created_at',
            field=models.IntegerField(default=1735923725),
        ),
        migrations.AlterField(
            model_name='orderbatch',
            name='updated_at',
            field=models.IntegerField(default=1735923725),
        ),
    ]
