# Generated by Django 4.2.16 on 2025-01-02 11:28

from django.db import migrations, models
import inventory_svs.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_svs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBatchCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productBatch_id', models.UUIDField(db_index=True, verbose_name=inventory_svs.models.ProductBatch)),
                ('available_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='productbatchledger',
            name='available_quantity',
        ),
        migrations.AlterField(
            model_name='productbatchledger',
            name='order_time',
            field=models.IntegerField(default=1735817310),
        ),
    ]
