# Generated by Django 4.2.16 on 2025-01-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_svs', '0005_alter_productbatchledger_order_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatchledger',
            name='order_time',
            field=models.IntegerField(default=1735833253),
        ),
    ]
