# Generated by Django 4.2.16 on 2025-01-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_svs', '0006_alter_productbatchledger_order_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbatch',
            old_name='producBatch_mrp',
            new_name='productBatch_mrp',
        ),
        migrations.AlterField(
            model_name='productbatchledger',
            name='order_time',
            field=models.IntegerField(default=1735839673),
        ),
    ]
