# Generated by Django 4.2.16 on 2025-01-03 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_svs', '0007_rename_producbatch_mrp_productbatch_productbatch_mrp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='productBatch_DateOfExpiry',
            field=models.DateField(default=datetime.date(2124, 12, 10)),
        ),
        migrations.AlterField(
            model_name='productbatchledger',
            name='order_time',
            field=models.IntegerField(default=1735908728),
        ),
    ]
