# Generated by Django 4.2.16 on 2025-01-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_svs', '0008_alter_productbatch_productbatch_dateofexpiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatchledger',
            name='order_time',
            field=models.IntegerField(default=1735910163),
        ),
    ]
