# Generated by Django 4.2.16 on 2025-01-03 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_svs', '0009_alter_productbatchledger_order_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbatch',
            old_name='productBatch_inbound_by',
            new_name='productBatch_created_by',
        ),
        migrations.RemoveField(
            model_name='productbatch',
            name='productBatch_inbound_date',
        ),
        migrations.AddField(
            model_name='productbatch',
            name='productBatch_created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 17, 2, 5, 344245)),
        ),
        migrations.AlterField(
            model_name='productbatchledger',
            name='order_time',
            field=models.IntegerField(default=1735923725),
        ),
    ]
